spring:
  application:
    name: ai-course-advisor

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
      embedding:
        model: nomic-embed-text

server:
  port: ${PORT:8082}